# Generated by Django 3.0.3 on 2020-10-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currentELO',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='highestELO',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lowestELO',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='realname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
