# Generated by Django 3.0.3 on 2020-10-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0002_auto_20201020_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=20)),
                ('player2', models.CharField(max_length=20)),
                ('result', models.IntegerField()),
                ('player1Elo', models.IntegerField()),
                ('player2Elo', models.IntegerField()),
                ('dateTime', models.IntegerField()),
            ],
        ),
    ]
