# Generated by Django 3.0.3 on 2020-10-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0006_auto_20201021_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1ELO',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2ELO',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.FloatField(),
        ),
    ]
