# Generated by Django 3.0.3 on 2020-10-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0007_auto_20201021_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1ELO',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2ELO',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currentELO',
            field=models.IntegerField(default=1200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='highestELO',
            field=models.IntegerField(default=1200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lowestELO',
            field=models.IntegerField(default=1200),
        ),
    ]
