# Generated by Django 3.0.3 on 2020-10-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0008_auto_20201021_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1ELO',
            field=models.FloatField(),
        ),
    ]
